services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - db-data:/var/lib/mysql

  # sonarqube:
  #   container_name: sonarqube
  #   image: sonarqube:latest
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  #     - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
  #     - SONAR_JDBC_USERNAME=sonar
  #     - SONAR_JDBC_PASSWORD=sonar
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_logs:/opt/sonarqube/logs
  #     - sonarqube_temp:/opt/sonarqube/temp

  # sonarqube-db:
  #   container_name: sonarqube-db
  #   image: postgres:alpine
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #     - POSTGRES_DB=sonar
  #   volumes:
  #     - sonarqube_db:/var/lib/postgresql/data

volumes:
  db-data:
  # sonarqube_data:
  # sonarqube_extensions:
  # sonarqube_logs:
  # sonarqube_temp:
  # sonarqube_db:
